### ISSUE TITLE
Design for drag-and-drop over state

### ISSUE THREAD

**Issue by mingard** [dadi/publish#150]
UI required in support of the drag-and-drop asset upload method.
<img width="355" alt="screen shot 2017-04-03 at 13 25 13" src="https://cloud.githubusercontent.com/assets/1352469/24609039/0a27d43c-1871-11e7-9a54-6d57135890eb.png">

**Comment by mingard** [comment]
ping @abovebored

**Comment by abovebored** [comment]
Check out the active state for `.c-upload` in the mockup `index_media.html`

<img width="377" alt="screen shot 2017-04-25 at 17 30 36" src="https://cloud.githubusercontent.com/assets/649231/25396608/0c0e560e-29dd-11e7-9788-4ac651a5f2ff.png">

```CSS
.u-active {
    border: 1px solid #4a91ff;
    background: #e3eeff;
    box-shadow: 0 0 14px rgba(0,0,0,.1) inset;
}
```

Bonus points for a smooth transition on dragover 🌈
